### ISSUE TITLE
Too Awesome

### ISSUE THREAD

**Issue by matdave** [sergant210/tagElementPlugin#3]
This thing is too awesome, and improves my productivity a little more than I had hoped for.  Is there any way to tone it down a bit?

**Comment by donShakespeare** [comment]
We need more issues like this...actually especially at the airport: "okay fellows we found a rather huge bag of money - that's the reason we are behind schedule, and we might take a little longer before takeoff because the tower has just now instructed us to distribute the money unevenly to all of you passengers."
